name: "automated test"

on:
  push:
  pull_request:

jobs:
  test-on-linux:
    name: "test on Linux"
    runs-on: ubuntu-latest
    steps:
      - name: "install latest nim"
        working-directory: /opt
        run: |
          curl https://nim-lang.org/install_unix.html | grep -o "['\"]/download/nim-.*-linux_x64.tar.xz['\"]" | sed "s/[\"']//g" | xargs -I {} curl -O https://nim-lang.org{}
          tar xf nim-*-linux_x64.tar.xz && rm nim-*-linux_x64.tar.xz
          ls . | grep nim | xargs -I {} echo /opt/{}/bin >> $GITHUB_PATH
      - name: "clone snowie"
        uses: actions/checkout@v2
      - name: "run snowie tests"
        run: nimble test -d:release
  test-on-macos:
    name: "test on macOS"
    runs-on: macos-latest
    steps:
      - name: "install latest nim"
        run: brew install nim
      - name: "clone snowie"
        uses: actions/checkout@v2
      - name: "run snowie tests"
        run: nimble test -d:release
  test-on-windows:
    name: "test on Windows"
    runs-on: windows-latest
    steps:
      - name: "install latest nim"
        run: |
          choco install nim --no-progress
          echo (Get-ChildItem -Path C:\tools\Nim\nim-*\bin | % { $_.FullName }) | Out-File -FilePath $env:GITHUB_PATH -Append
      - name: "clone snowie"
        uses: actions/checkout@v2
      - name: "run snowie tests"
        run: nimble test -d:release
